# Generated by Django 6.0.6 on 2026-06-25 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('technical', 'Technical'), ('professional', 'Professional')], default='technical', max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Percentage (0-100)')),
            ],
            options={
                'ordering': ['category', '-proficiency'],
            },
        ),
    ]
